// Code generated by MockGen. DO NOT EDIT.
// Source: domain/taco/repository/taco_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	taco "github.com/fwchen/jellyfish/domain/taco"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockRepository) ListTacos(userID string, filter taco.ListTacoFilter) ([]taco.Taco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", userID, filter)
	ret0, _ := ret[0].([]taco.Taco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockRepositoryMockRecorder) ListTacos(userID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).ListTacos), userID, filter)
}

// Save mocks base method
func (m *MockRepository) SaveTaco(taco *taco.Taco) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", taco)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save
func (mr *MockRepositoryMockRecorder) SaveTaco(taco interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).SaveTaco), taco)
}

// FindById mocks base method
func (m *MockRepository) FindTaco(tacoID string) (*taco.Taco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", tacoID)
	ret0, _ := ret[0].(*taco.Taco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById
func (mr *MockRepositoryMockRecorder) FindTaco(tacoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockRepository)(nil).FindTaco), tacoID)
}
