ALTER TABLE todos ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE todos ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMPTZ;