datasource:
  rds:
    database_url: postgres://postgres:mysecretpassword@localhost:5432/jellyfish?sslmode=disable

application:
  addr: 127.0.0.1:8180
  jwt_secret: jellyfish-app-tXQhvSMWMS11qZ9euEhE6lf2ferf0FR6RYGd8iMXiTxxXtJ1XDVdTXPaLtV12ZGp  # CHANGE_ME
  jwt_header_key: "App-Authorization"

logger:
  level: debug
  output_paths: # NOTE: viper not support read a environment array var
    - "stdout"
    # - "/var/log/jellyfish_log"

storage:
  endpoint: "localhost:9100"
  access_key_id: "minio"
  secret_access_key_id: "miniostorage"
  use_ssl: false
  location: "us-east-1"

bucket:
  image: "jellyfish-image-bucket"

notification:
  endpoint: "http://127.0.0.1:9099"